global:
  ramdom_seed: 42
  pre_trained_model_name: "bert-base-cased"

dataset:
  apps_dataset_path: data/raw/apps.csv
  reviews_datase_path: data/raw/reviews.csv

split:
  train_split_path: data/processed/train_split.csv
  val_split_path: data/processed/val_split.csv
  test_split_path: data/processed/test_split.csv

train:
  batch_size: 16
  max_len_tokenks: 160
  epochs: 10
